### ISSUE TITLE
iOS sample ObjC

### ISSUE THREAD

**Issue by PsyKoMari** [blackmenthor/flutter-branch-io-ios-sample#1]
I'm developing a flutter application and I really like branch.io and your flutter plugin.
But I have the generated Xcode project in ObjC, can you please add it to your sample?

**Comment by abumoallim** [comment]
Any update on this? even I need ObjC code for the same

**Comment by blackmenthor** [comment]
Hi!

Sorry but currently i didn't own any mac for maybe 3 more weeks or so.

But definitely will create them once i got it.

**Comment by blackmenthor** [comment]
Hi!

Now you don't have to override the `AppDelegate` anymore on version 1.0.1, feel free to use that.

Thanks!
